name: "ðŸ’° api-user â€“ Docker Build & GitOps Dispatch"

on:
  push:
    branches: [ main, develop ]
  workflow_dispatch: {}

permissions:
  contents: read

concurrency:
  group: api-user-${{ github.ref_name }}
  cancel-in-progress: true

env:
  SERVICE: user
  IMAGE:   ${{ secrets.DOCKER_USERNAME }}/api-user
  DEVOPS_REPO: 3-mnms/gitops-repo

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      - run: chmod +x ./gradlew
      - run: ./gradlew bootJar --no-daemon

      - name: â±ï¸ Tag
        run: |
          TS=$(date -u +'%Y%m%d%H%M%S')
          echo "TAG_AMD=v${TS}-win" >> $GITHUB_ENV
          echo "TAG_ARM=v${TS}-mac" >> $GITHUB_ENV
          echo "TAG=v${TS}-win" >> $GITHUB_ENV

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE }}
          tags: |
            type=raw,value=${{ env.TAG_AMD }}
            type=raw,value=${{ env.TAG_ARM }}
            type=raw,value=latest
            type=sha
            type=raw,value=latest,enable=${{ github.ref_name == 'main' }}

      - uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # - name: Dispatch to GitOps (develop-gke + develop-aws)
      #   if: ${{ github.ref_name == 'develop' }}
      #   uses: peter-evans/repository-dispatch@v3
      #   with:
      #     token:  ${{ secrets.GH_PAT }}
      #     repository: ${{ env.DEVOPS_REPO }}
      #     event-type: image-updated
      #     client-payload: |
      #       {
      #         "service": "${{ env.SERVICE }}",
      #         "image":   "${{ env.IMAGE }}",
      #         "tag":     "${{ env.TAG }}",
      #         "targets": "develop-gke,develop-aws"
      #       }

      # - name: Dispatch to GitOps (prod)
      #   if: ${{ github.ref_name == 'main' }}
      #   uses: peter-evans/repository-dispatch@v3
      #   with:
      #     token:  ${{ secrets.GH_PAT }}
      #     repository: ${{ env.DEVOPS_REPO }}
      #     event-type: image-updated
      #     client-payload: |
      #       {
      #         "service": "${{ env.SERVICE }}",
      #         "image":   "${{ env.IMAGE }}",
      #         "tag":     "${{ env.TAG }}",
      #         "env":     "prod"
      #       }
